package console;

import java.awt.EventQueue;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.IOException;
import java.sql.SQLException;

import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.border.EmptyBorder;
import javax.swing.SwingConstants;
import java.awt.Color;

public class Admin extends JFrame {

	private JPanel contentPane;

	/**
	 * Launch the application.
	 */
	public static void main(String[] args) {
		EventQueue.invokeLater(new Runnable() {
			public void run() {
				try {
					Admin frame = new Admin();
					frame.setVisible(true);  //for running individually
					frame.setTitle("Typing S/W PRO");
				} catch (Exception e) {
					e.printStackTrace();
				}
			}
		});
	}

	/**
	 * Create the frame.
	 */
	public Admin() {
		setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
		setBounds(100, 100, 393, 295);
		contentPane = new JPanel();
		contentPane.setBorder(new EmptyBorder(5, 5, 5, 5));
		
		JLabel lblNewLabel = new JLabel("Designed and Programmed By NitinBhandari");
		contentPane.add(lblNewLabel);
		lblNewLabel.setForeground(Color.WHITE);
		lblNewLabel.setFont(new Font("Gill Sans MT", Font.BOLD | Font.ITALIC, 18));
		lblNewLabel.setBounds(10, 11, 360, 31);
		
		setContentPane(contentPane);
		contentPane.setLayout(null);
		JLabel bgimage = new JLabel("");
		bgimage.setBounds(0, 0, 377, 256);
		contentPane.add(bgimage);
		bgimage.setIcon(new ImageIcon(Admin.class.getResource("/me.png")));
		
		JButton btnNewButton_1 = new JButton("Stats");
		bgimage.add(btnNewButton_1);
		btnNewButton_1.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent arg0) {
				try {
					HighScore h=  new HighScore();
					h.setVisible(true);
					h.setResizable(false);
					h.setTitle("Typing S/W PRO");
					h.setLocationRelativeTo(null);
				} catch (SQLException e) {
					e.printStackTrace();
				}
			}
		});
		
		btnNewButton_1.setBounds(10, 206, 89, 23);
		
		JButton btnNewButton = new JButton("Add File");
		bgimage.add(btnNewButton);
		btnNewButton.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				int response = JOptionPane.showConfirmDialog(null, "1. Place The file in the source directory"+"\n"+"2.  File will be generated by the name new.txt in the source folder");
				if(response == 0) {  //0==yes,1==no,2==cancel
				try {
					Filecreator file = new Filecreator();
				} catch (IOException e1) {
					// TODO Auto-generated catch block
					e1.printStackTrace();
				}
				}
	
			}
		});
		btnNewButton.setBounds(10, 167, 89, 23);
		
		JButton btnNewButton_2 = new JButton("Clear D Entries");
		btnNewButton_2.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent arg0) {
				DBMS d = new DBMS();
				try {
					d.clearDuplicateEntries();
				} catch (SQLException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
			}
		});
		bgimage.add(btnNewButton_2);
		btnNewButton_2.setBounds(10, 125, 109, 23);
		

		
	
	}
}
